### ISSUE TITLE
[BUG] Broken badge

### ISSUE THREAD

**Issue by Pradumnasaraf** [Panquesito7/Panquesito7#16]
### Description of the bug

Looks like the URL can't able to fetch the Image

### Please add screenshots (if applicable)

![Screenshot from 2022-06-08 10-21-01](https://user-images.githubusercontent.com/51878265/172534399-26161dfe-ade2-4966-916b-06d9e1778533.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Panquesito7** [comment]
Hey there! Yeah, it looks like it's bugged, but if you refresh the page twice or once, and then it comes back.

![image](https://user-images.githubusercontent.com/51391473/172682093-a18343e9-19ea-410b-bd83-bf2aa5d79c99.png)

**Comment by Pradumnasaraf** [comment]
> Hey there! Yeah, it looks like it's bugged, but if you refresh the page twice or once, and then it comes back.
> 
> ![image](https://user-images.githubusercontent.com/51391473/172682093-a18343e9-19ea-410b-bd83-bf2aa5d79c99.png)

oh great, Badges are always tricky.

**Comment by Panquesito7** [comment]
Yeah! Anyways, thanks for reporting! Closing.
